// Generated by CoffeeScript 1.3.3
(function() {

  describe("Model.Local", function() {
    var User;
    User = void 0;
    beforeEach(function() {
      return User = Spine.Model.setup("User", ["name"]);
    });
    it("should persist attributes", function() {
      User.extend(Spine.Model.Local);
      User.create({
        name: "Bob"
      });
      User.fetch();
      expect(User.first()).toBeTruthy();
      return expect(User.first().name).toEqual("Bob");
    });
    it("should work with cIDs", function() {
      User.refresh([
        {
          name: "Bob",
          id: "c-1"
        }, {
          name: "Bob",
          id: "c-3"
        }, {
          name: "Bob",
          id: "c-2"
        }
      ]);
      return expect(User.idCounter).toEqual(3);
    });
    return it("should work with a blank refresh", function() {
      User.refresh([]);
      return expect(User.idCounter).toEqual(0);
    });
  });

}).call(this);
